app:
  id: 100004468

apollo:
  # 本地启动 apollo 集群 进行调用
  meta: http://192.168.233.135:8080,http://192.168.199.13:8080
  #cluster: myCluster
  #cacheDir: /opt/testDir
  bootstrap:
    enable: true
    namespaces: application

env: DEV
