server:
  port: 8060


#日志信息
logging:
  config: classpath:logback.xml

spring:
  #yml redis 部分
  redis:
    database: 0
    host: localhost
    port: 6379
    password: dkzredis
    jedis:
      pool:
        # 最大等待时间 ms
        max-wait: 10000
        max-idle: 8
        min-idle: 0
    timeout: 1000

